# Generated by Django 5.1.2 on 2025-03-24 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0071_alter_budgetplanner_post_debt_repayments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mortgagefeatures",
            name="applicant",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicant_mortgage_features",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
